In [1]:
from ase.io import read, write, Trajectory
import numpy as np

In [2]:
def CoM(clus):
    """
    Support function to set the origin of the cluster at the centre of the mass
    """
    (cx, cy, cz) = clus.get_center_of_mass()
    new_xyz = []
    for i, a in enumerate(clus):
        x, y, z = a.position
        x -= cx
        y -= cy
        z -= cz
        new_xyz.append((x, y, z))
    clus.set_positions(new_xyz)
    return clus

In [3]:
def checkSimilar(clus1, clus2):

    """Check whether two clusters are similar or not by comparing their moments of inertia"""
    Inertia1 = clus1.get_moments_of_inertia()
    Inertia2 = clus2.get_moments_of_inertia()
    # print(Inertia1, Inertia2, 'diff: ', Inertia1-Inertia2)

    tol = 0.01
    if (
        Inertia1[0] * (1 - tol) <= Inertia2[0] <= Inertia1[0] * (1 + tol)
        and Inertia1[1] * (1 - tol) <= Inertia2[1] <= Inertia1[1] * (1 + tol)
        and Inertia1[2] * (1 - tol) <= Inertia2[2] <= Inertia1[2] * (1 + tol)
    ):
        similar = True
    else:
        similar = False

    return similar

In [4]:
#
        

In [5]:
#

In [6]:
#

In [33]:
num_check_similar = 0
num_check_not_similar = 0
diff_dist_abs_sum_list = []
diff_dist_abs_sum_list_false = []
diff_ene_list = []
non_similar_clus = []
for k in range(1,25):
    file1  = 'mut_after_relax_gen'+str(k)+'.traj'
    file2  = 'vasp_mut_after_relax_gen'+str(k)+'.traj'

    traj1 = Trajectory(file1)
    traj2 = Trajectory(file2)
    
    for i in range(len(traj1)):
        #print(k, i)
        clus1 = traj1[i]
        clus2 = traj2[i]
        
        ene1 = clus1.get_potential_energy()
        ene2 = clus2.get_potential_energy()
        diff_ene = ene1 - ene2
        
        dist1 = clus1.get_all_distances() 
        dist2 = clus2.get_all_distances()
        diff_dist = dist1 - dist2
        diff_dist_abs = np.absolute(diff_dist)
        diff_dist_abs_sum = np.sum(diff_dist_abs) / len(diff_dist)**2
        #print(np.sum(diff_dist_abs, axis=0))
        
        inertia1 = clus1.get_moments_of_inertia()
        inertia2 = clus2.get_moments_of_inertia()
        diff_inertia = inertia1 - inertia2
        
      
        if checkSimilar(clus1, clus2) == True:
            if diff_dist_abs_sum > 0.02:
                if abs(diff_ene) > 0.01:
                    print((k, i),diff_dist_abs_sum, diff_ene, diff_inertia )
                    non_similar_clus.append((k,i))
        else:
            non_similar_clus.append((k,i))
            diff_dist_abs_sum_list_false.append(diff_dist_abs_sum)
            print((k, i),diff_dist_abs_sum, diff_ene, diff_inertia )


print('\n')            
print(sorted(diff_dist_abs_sum_list)) 
#print(len(diff_dist_abs_sum_list))
#print(sorted(diff_ene_list))
#print(num_checksimilar)
#print(non_similar_clus)
#print(len(non_similar_clus))
#print(sorted(diff_dist_abs_sum_list_false)) 
#print(len(diff_dist_abs_sum_list_false))

(2, 9) 0.06313870837466182 -0.038007690000000593 [ 34.21808831 -31.80388226 -52.38093971]
(12, 2) 0.07486044699011189 -0.040179639999998074 [84.26571478 14.17467188 -2.95137946]
(14, 6) 0.020960516268649327 -0.011504370000004371 [-50.50145458  88.97356013  58.89471659]
(22, 9) 0.023619148755338385 -0.0458201199999948 [-10.51001081 -76.72514584 -33.86914195]


[0.0013047696661483976, 0.001911084004444355, 0.002106838957791967, 0.0022235252030516767, 0.0027062441496608983, 0.0027062451801463314, 0.0029871070214014216, 0.0033275203944837274, 0.004099311724493061, 0.004099312529099723, 0.004251991442785638, 0.004390553516346648, 0.004409047117775448, 0.004485621820889289, 0.0053368581531037275, 0.005375899395526389, 0.005376719434275586, 0.00542309791554231, 0.0054230980428009515, 0.005423098062370936, 0.00542310008094948, 0.005482895636902584, 0.005519271967132831, 0.005613166467534049, 0.005623163669894779, 0.005810481383808987, 0.0058196579341701395, 0.006306166724424526, 0.006638047152

In [8]:
'''
num_checksimilar = 0
diff_dist_abs_sum_list = []
diff_dist_abs_sum_list_false = []
diff_ene_list = []
non_similar_clus = []
for k in range(1,25):
    file1  = 'mut_after_relax_gen'+str(k)+'.traj'
    file2  = 'vasp_mut_after_relax_gen'+str(k)+'.traj'

    traj1 = Trajectory(file1)
    traj2 = Trajectory(file2)
    
    for i in range(len(traj1)):
        print(k, i)
        clus1 = traj1[i]
        clus2 = traj2[i]
        
        ene1 = clus1.get_potential_energy()
        ene2 = clus2.get_potential_energy()
        diff_ene = ene1 - ene2
        
        dist1 = clus1.get_all_distances() 
        dist2 = clus2.get_all_distances()
        diff_dist = dist1 - dist2
        diff_dist_abs = np.absolute(diff_dist)
        diff_dist_abs_sum = np.sum(diff_dist_abs)
        #print(np.sum(diff_dist_abs, axis=0))
        
        inertia1 = clus1.get_moments_of_inertia()
        inertia2 = clus2.get_moments_of_inertia()
        diff_inertia = inertia1 - inertia2
        
        #if diff_ene > 0.01:
        
        if checkSimilar(clus1, clus2) == True:
            print(diff_ene)
            #print(diff_dist)
            print(diff_inertia)
            print(checkSimilar(clus1, clus2))
            print(diff_dist_abs_sum)
            diff_dist_abs_sum_list.append(diff_dist_abs_sum)
            diff_ene_list.append(diff_ene)
        else:
            num_checksimilar = num_checksimilar +1
            non_similar_clus.append((k,i))
            diff_dist_abs_sum_list_false.append(diff_dist_abs_sum)

            #print(diff_ene)
            #print(diff_dist)
            #print(diff_inertia)
            
print(sorted(diff_dist_abs_sum_list)) 
print(len(diff_dist_abs_sum_list))
print(sorted(diff_ene_list))
print(num_checksimilar)
print(non_similar_clus)
print(len(non_similar_clus))
print(sorted(diff_dist_abs_sum_list_false)) 
print(len(diff_dist_abs_sum_list_false))
'''

1 0
1 1
0.0004019500000040921
[  3.56942512  -5.89638834 -11.15144796]
True
1.7798094798175859
1 2
0.0024848600000026977
[  3.86613746 -23.0283148  -17.03941907]
True
2.853819699974941
1 3
0.002892899999999088
[ 21.85078287 -20.46945144  20.67983693]
True
2.872381698020014
1 4
1 5
-0.0056708800000038195
[18.65214481  3.5117326  -7.07067895]
True
1.148319186147658
1 6
-0.0036767600000047196
[ -3.22749118  10.21337471 -44.1138531 ]
True
2.9664073224477336
1 7
1 8
1 9
-0.006935250000005055
[ 24.31510437 -60.09335608 -44.89258244]
True
2.884031336397954
2 0
5.844000000365668e-05
[ 53.37586447 -42.74438411 -53.46863067]
True
3.7959140410568635
2 1
-0.0012013600000031488
[-6.18895257 11.13627252 26.63820085]
True
1.4874832342551008
2 2
2 3
-0.0018735599999999408
[-5.99535215  8.00380844 20.43681642]
True
1.4369706156887165
2 4
2 5
2 6
2 7
2 8
2 9
-0.038007690000000593
[ 34.21808831 -31.80388226 -52.38093971]
True
16.163509343913425
3 0
7.717000000440066e-05
[ 17.15679149 -31.35020241   9.865